packages:
  - packages/*
  - apps/**/*

catalog:
  '@arethetypeswrong/core': ^0.18.2
  '@total-typescript/tsconfig': ^1.0.4
  '@types/node': ^24.4.0
  '@vitest/coverage-v8': ^3.2.4
  publint: ^0.3.12
  tsdown: ^0.12.9
  type-fest: ^4.41.0
  typescript: ^5.8.3
  vitest: ^3.2.4

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - rolldown
  - sharp
  - unrs-resolver
  - workerd

overrides:
  '@mcansh/http-helmet': workspace:*
  '@mcansh/url': workspace:*
  '@mcansh/vitest-response-matchers': workspace:*

shellEmulator: true
