packages:
  - packages/*
  - apps/**/*

catalog:
  '@arethetypeswrong/core': ^0.18.4
  '@total-typescript/tsconfig': ^1.0.4
  '@types/node': ^26.1.0
  '@vitest/coverage-v8': ^4.1.9
  publint: ^0.3.21
  tsdown: ^0.22.3
  type-fest: ^5.7.0
  typescript: ^6.0.3
  vitest: ^4.1.9

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - rolldown
  - sharp
  - unrs-resolver
  - workerd

overrides:
  '@mcansh/create-temporary-files': workspace:*
  '@mcansh/http-helmet': workspace:*
  '@mcansh/url': workspace:*
  '@mcansh/vitest-response-matchers': workspace:*

shellEmulator: true
