name: autofix.ci

on:
  pull_request:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5

      - name: ⎔ Enable corepack
        run: corepack enable

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: 🟧 Install dependencies
        run: pnpm install --recursive --frozen-lockfile --strict-peer-dependencies

      - run: pnpm run format

      - uses: autofix-ci/action@v1
