# Experimental releases are handled a bit differently than standard releases.
# Experimental releases can be branched from anywhere as they are not intended
# for general use, and all packages will be versioned and published with the
# same hash for testing.
#
# This workflow runs when an experimental version tag is pushed.
# Unlike standard releases created via Changesets, only one tag
# should be created for all packages.
#
# To create a release:
# - Create a new branch for the release: git checkout -b `release-experimental`
#   - IMPORTANT: You should always create a new branch so that the version
#     changes don't accidentally get merged into `dev` or `main`. The branch
#     name must follow the convention of `release-experimental` or
#     `release-experimental-[feature]`.
# - Make whatever changes you need and commit them:
#   - `git add . && git commit "experimental changes!"`
# - Update version numbers and create a release tag:
#   - `pnpm run version:experimental`
# - Push to GitHub:
#   - `git push origin --follow-tags`
# - Pushing the experimental tag triggers the workflow that publishes to npm.

name: 🚀 Release (experimental)
on:
  push:
    tags:
      - "v0.0.0-experimental*"

permissions:
  contents: read
  id-token: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true

jobs:
  release:
    name: 🧑‍🔬 Experimental Release
    if: |
      github.repository == 'mcansh/packages' &&
      contains(github.ref, 'experimental')
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: ⎔ Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".node-version"

      - name: 🟧 Setup pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        with:
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
              cwd: ./

      - name: 🏗 Build
        run: pnpm run build

      - name: 🔐 Setup npm auth
        run: |
          echo "registry=https://registry.npmjs.org" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: 🚀 Publish
        run: npm run publish
